[[main]]
  name = "About Us"
  url = "/about/"
  weight = 1

[[main]]
  name = "Creations"
  url = "/creations/"
  weight = 2

[[main]]
  name = "Devlog"
  url = "/devlog/"
  weight = 3

[[main]]
  name = "Contact"
  url = "/contact/"
  weight = 4

[[main]]
  name = "Instagram"
  parent = "Contact"
  pre = "instagram"
  url = "https://www.instagram.com/rustlingleavesgames/"

[[main]]
  name = "Facebook"
  parent = "Contact"
  pre = "facebook"
  url = "https://www.facebook.com/people/Rustling-Leaves-Games/61583138965806/"

[[main]]
  name = "LinkedIn"
  parent = "Contact"
  pre = "linkedin"
  url = "https://www.linkedin.com/company/rustling-leaves-games/posts/?feedView=all"

[[main]]
  name = "Email"
  parent = "Contact"
  pre = "email"
  url = "mailto://rustlingleavesinteractive@gmail.com"





[[footer]]
  name = "Instagram"
  pre = "instagram"
  url = "https://www.instagram.com/rustlingleavesgames/"

[[footer]]
  name = "Facebook"
  pre = "facebook"
  url = "https://www.facebook.com/people/Rustling-Leaves-Games/61583138965806/"

[[footer]]
  name = "LinkedIn"
  pre = "linkedin"
  url = "https://www.linkedin.com/company/rustling-leaves-games/posts/?feedView=all"

[[footer]]
  name = "Email"
  pre = "email"
  url = "mailto://rustlingleavesinteractive@gmail.com"