baseURL = "https://www.rustlingleavesgames.com/"
languageCode = 'en-us'
title = 'Rustling Leaves Games'
buildFuture = true

[module]
  [[module.imports]]
    path = "github.com/nunocoracao/blowfish/v2"

[params]
  defaultTheme = "auto"
  showReadingTime = true
  mainSections = ["posts"]
  description = "Weâ€™re a small indie game studio with one big beLEAF, that every game should tell a story."
  logo = "images/logos/logo.png"
  colorScheme="brand"
  enableSearch = false

[params.homepage]


[params.footer]
  showAppearanceSwitcher = false
  showMenu = true
  showThemeAttribution = false
  showScrollToTop = true

[menus.footer]
  [[menu.social]]
    name="Social"
  

[params.assets]
  customCSS = ["css/custom.css"]
