baseURL = 'https://timpoliquin.github.io/company-website-example/'
languageCode = 'en-us'
title = 'Rustling Leaves Games'
theme = 'blowfish'
buildFuture = true

[params]
  defaultTheme = "auto"
  showReadingTime = true
  mainSections = ["posts"]
  description = "Weâ€™re a small indie game studio with one big beLEAF, that every game should tell a story."
  logo = "images/logo.png"
  colorScheme="brand"
  enableSearch = false

[params.homepage]


[params.footer]
  showAppearanceSwitcher = false
  showMenu = true
  showThemeAttribution = false
  showScrollToTop = true

[menus.footer]
  [[menu.social]]
    name="Social"
  

[params.assets]
  customCSS = ["css/custom.css"]
